# Generated by Django 4.0.10 on 2024-10-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_rename_restaurant_id_review_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('five', '5'), ('four', '4'), ('three', '3'), ('two', '2'), ('one', '1')], default='five', max_length=6),
        ),
    ]
